name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
        # - '2.1'
        # - '2.2'
        # - '2.3'
        # - '2.4'
        # - '2.5'
        # - '2.6'
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
        - head
        gemfile:
        - 'Gemfile'
        # - 'gemfiles/Gemfile.rails3_0'
        # - 'gemfiles/Gemfile.rails3_1'
        # - 'gemfiles/Gemfile.rails4_1'
        - 'gemfiles/Gemfile.rails6_1'
        - 'gemfiles/Gemfile.rails7_0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        # bundler: 1
        # bundler-cache: true
    - name: Bundle install
      run: |
        export BUNDLE_GEMFILE=${{ matrix.gemfile }}
        export BUNDLE_PATH=vendor/bundle
        bundle install
    - name: Database setup
      run: |
        export BUNDLE_GEMFILE=${{ matrix.gemfile }}
        export BUNDLE_PATH=vendor/bundle
        cd spec/dummy && bundle install && rake db:migrate RAILS_ENV=test
    - name: Run tests
      run: |
        export BUNDLE_GEMFILE=${{ matrix.gemfile }}
        export BUNDLE_PATH=vendor/bundle
        xvfb-run rake
